### ISSUE TITLE
windows11下测试帧率很低

### ISSUE THREAD

**Issue by jiayao-zhang** [pysrc/diffscreen#1]
屏幕是2k，实际帧率估计只有一两帧。屏幕改成1080p会好很多。

**Comment by pysrc** [comment]
> 屏幕是2k，实际帧率估计只有一两帧。屏幕改成1080p会好很多。

因为是基于截屏实现的，如果分辨率太大了会导致图像矩阵太大运算负担加重，所以需要适当减小分辨率
