### ISSUE TITLE
BUG: 无法在win server2022环境下运行

### ISSUE THREAD

**Issue by huangkaoya** [pysrc/diffscreen#3]
![image](https://github.com/pysrc/diffscreen/assets/29002330/89deb8b6-62cd-4120-b5e8-a5810f856425)

**Comment by pysrc** [comment]
你端口被占了吧，改个端口



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月8日(周四) 晚上11:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [pysrc/diffscreen] BUG: 无法在win server2022环境下运行 (Issue #3)

**Comment by pysrc** [comment]
@huangkaoya 解决了吗，解决了的话我就关闭issues了
