### ISSUE TITLE
windows10出现bug

### ISSUE THREAD

**Issue by QwindF** [pysrc/diffscreen#4]
环境
![image](https://github.com/pysrc/diffscreen/assets/87116340/79c9fa0b-ef95-40d2-81d0-6f9b39013007)
操作：
先运行了`dsserver.exe`出现命令行窗口，启动`dsclient.exe`然后login时`dsserver.exe`自动结束，界面表现为灰色
![image](https://github.com/pysrc/diffscreen/assets/87116340/0d43bc0b-2866-4979-bdbc-a20080d3097e)
![image](https://github.com/pysrc/diffscreen/assets/87116340/3c8115c4-5e74-4cb8-b791-d09a91336b60)
![image](https://github.com/pysrc/diffscreen/assets/87116340/e6ef4891-fba4-43c0-b25c-efc599099d9a)

**Comment by pysrc** [comment]
用cmd打开看看报错呢？

**Comment by QwindF** [comment]
> 用cmd打开看看报错呢？
在这里
![image](https://github.com/pysrc/diffscreen/assets/87116340/42ad336a-f7be-4056-a68c-576639023aef)
![image](https://github.com/pysrc/diffscreen/assets/87116340/22df7276-8c10-4ce4-b792-297b0aeee187)

**Comment by pysrc** [comment]
你的电脑没有GPU吗，这个截图是需要GPU支持的哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月23日(周五) 中午11:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pysrc/diffscreen] windows10出现bug (Issue #4)




  
用cmd打开看看报错呢？
 在这里

**Comment by QwindF** [comment]
有啊，
![image](https://github.com/pysrc/diffscreen/assets/87116340/36eedfd5-00eb-4923-8a49-d41c6d23a445)

**Comment by pysrc** [comment]
这就触及到我的知识盲区了，你可以用scrap这个库截图试试，地址https://github.com/quadrupleslap/scrap

**Comment by QwindF** [comment]
好的
